# Comprehensive Indonesian Slang, Abbreviation & Colloquial dictionary
SLANG_WORDS = {
    # Negation
    "gak": "tidak",
    "ga": "tidak",
    "nggak": "tidak",
    "ngga": "tidak",
    "ndak": "tidak",
    "kagak": "tidak",
    "tak": "tidak",
    "tdk": "tidak",
    "g": "tidak",
    "gk": "tidak",
    "gpp": "tidak apa-apa",
    "gapapa": "tidak apa-apa",
    "gatau": "tidak tahu",
    "gajadi": "tidak jadi",
    "gamau": "tidak mau",
    
    # Common slang/chat words
    "bgt": "banget",
    "bngt": "banget",
    "bgtt": "banget",
    "bangeeet": "banget",
    "bgus": "bagus",
    "bgs": "bagus",
    "bguss": "bagus",
    "mantap": "mantap",
    "mantul": "mantap betul",
    "mntp": "mantap",
    "mantapp": "mantap",
    "keren": "keren",
    "krn": "karena",
    "karna": "karena",
    "krna": "karena",
    "jlek": "jelek",
    "jlk": "jelek",
    "jelekk": "jelek",
    "ancur": "hancur",
    "hancuur": "hancur",
    "kecewa": "kecewa",
    "kcewa": "kecewa",
    "kcwa": "kecewa",
    "puas": "puas",
    "puass": "puas",
    "rekomen": "rekomendasi",
    "recomended": "rekomendasi",
    "recom": "rekomendasi",
    "recommended": "rekomendasi",
    "recsel": "penjual rekomendasi",
    "ori": "original",
    "asli": "asli",
    "kw": "tiruan",
    "palsu": "palsu",
    "bener": "benar",
    "beneran": "benar",
    "bnr": "benar",
    "bener2": "benar-benar",
    "bangettt": "banget",
    "cepet": "cepat",
    "cpt": "cepat",
    "cepatt": "cepat",
    "lemot": "lambat",
    "lola": "lambat",
    "lelet": "lambat",
    "lambatt": "lambat",
    "packing": "kemasan",
    "packaging": "kemasan",
    "paking": "kemasan",
    "rapih": "rapi",
    "rapip": "rapi",
    "aman": "aman",
    "amann": "aman",
    "bocor": "bocor",
    "pecah": "pecah",
    "rusak": "rusak",
    "rsk": "rusak",
    "cacat": "cacat",
    "mulus": "mulus",
    "makasih": "terima kasih",
    "makasi": "terima kasih",
    "mksih": "terima kasih",
    "mksh": "terima kasih",
    "thx": "terima kasih",
    "thanks": "terima kasih",
    "thankyou": "terima kasih",
    "tengkyu": "terima kasih",
    "ty": "terima kasih",
    "klo": "kalau",
    "kl": "kalau",
    "kalo": "kalau",
    "klu": "kalau",
    "tp": "tapi",
    "tpi": "tapi",
    "tetapi": "tapi",
    "dgn": "dengan",
    "dg": "dengan",
    "denagn": "dengan",
    "utk": "untuk",
    "untk": "untuk",
    "tuk": "untuk",
    "buat": "untuk",
    "yg": "yang",
    "yng": "yang",
    "d": "di",
    "dr": "dari",
    "dri": "dari",
    "kpd": "kepada",
    "sm": "sama",
    "sama2": "sama-sama",
    "sbg": "sebagai",
    "sdh": "sudah",
    "udh": "sudah",
    "udah": "sudah",
    "dah": "sudah",
    "blm": "belum",
    "blum": "belum",
    "lom": "belum",
    "sy": "saya",
    "aq": "saya",
    "aku": "saya",
    "gua": "saya",
    "gw": "saya",
    "gue": "saya",
    "gw mah": "saya",
    "lu": "kamu",
    "lo": "kamu",
    "loe": "kamu",
    "elu": "kamu",
    "km": "kamu",
    "kmu": "kamu",
    "bisa": "bisa",
    "bs": "bisa",
    "bsa": "bisa",
    "gabisa": "tidak bisa",
    "gbs": "tidak bisa",
    "gakbisa": "tidak bisa",
    "tdk bs": "tidak bisa",
    "tdkbisa": "tidak bisa",
    "seller": "penjual",
    "seler": "penjual",
    "buyer": "pembeli",
    "olshop": "toko online",
    "kurir": "kurir",
    "kurirnya": "kurir",
    "ekspedisi": "ekspedisi",
    "ongkir": "ongkos kirim",
    "free ongkir": "gratis ongkos kirim",
    "fast respon": "respons cepat",
    "fast response": "respons cepat",
    "fast respond": "respons cepat",
    "slow respon": "respons lambat",
    "slow response": "respons lambat",
    "ramah": "ramah",
    "jutek": "tidak ramah",
    "nipu": "menipu",
    "penipu": "penipu",
    "tipu": "tipu",
    "sesuai": "sesuai",
    "ssuai": "sesuai",
    "pas": "sesuai",
    "mantab": "mantap",
    "mantabb": "mantap",
    "jos": "bagus",
    "joss": "bagus",
    "mantuliti": "mantap",
    "sip": "bagus",
    "siip": "bagus",
    "oke": "bagus",
    "ok": "bagus",
    "okay": "bagus",
    "good": "bagus",
    "nice": "bagus",
    "top": "bagus",
    "the best": "terbaik",
    "terbaik": "terbaik",
    "worth it": "sebanding",
    "worthed": "sebanding",
    "worth": "sebanding",
    "worthit": "sebanding",
    "parah": "parah",
    "parahh": "parah",
    "zonk": "kecewa",
    "nyesel": "menyesal",
    "menyesal": "menyesal",
    "kapok": "kapok",
    "rugi": "rugi",
    "bintang": "bintang",
    "bintang 5": "sangat puas",
    "bintang 1": "sangat kecewa"
}
