# Comprehensive Indonesian Stopwords list
INDONESIAN_STOPWORDS = {
    "ada", "adalah", "adanya", "adapun", "agak", "agaknya", "agar", "akan", "akankah", "akhir",
    "akhiri", "akhirnya", "aku", "akulah", "amat", "amatlah", "anda", "andalah", "antar",
    "antara", "antaranya", "apa", "apaan", "apabila", "apakah", "apalagi", "apatah", "artinya",
    "asal", "asalkan", "atas", "atau", "ataukah", "ataupun", "awal", "awalnya", "bagai",
    "bagaikan", "bagaimana", "bagaimanakah", "bagaimanapun", "bagi", "bagian", "bahkan",
    "bahwa", "bahwasanya", "baik", "bakal", "bakalan", "balik", "banyak", "bapak", "barangkali",
    "baru", "bawah", "beberapa", "begini", "beginian", "beginikah", "beginilah", "begitu",
    "begitukah", "begitulah", "begitupun", "bekerja", "belakang", "belakangan", "belum",
    "belumlah", "benar", "benarkah", "benarlah", "berada", "berakhir", "berakhirlah",
    "berakhirnya", "berapa", "berapakah", "berapalah", "berapapun", "berarti", "berawal",
    "berbagai", "berdatangan", "beri", "berikan", "berikut", "berikutnya", "berjumlah",
    "berkenaan", "berlainan", "berlalu", "berlangsung", "berlebihan", "bermacam", "bermaksud",
    "bermula", "bersama", "bersiap", "bertanya", "berturut", "bertutur", "berujar", "berupa",
    "besar", "betul", "betulkah", "biasa", "biasanya", "bila", "bilakah", "bisa", "bisakah",
    "boleh", "bolehkah", "bolehlah", "buat", "bukan", "bukankah", "bukanlah", "bukannya",
    "cuma", "percuma", "dahulu", "dalam", "dan", "dapat", "dari", "daripada", "dekat", "demi",
    "demikian", "demikianlah", "dengan", "depan", "di", "dia", "diakhiri", "diakhirinya",
    "dialah", "diantara", "diantaranya", "diberi", "diberikan", "diberikannya", "dibuat",
    "dibuatnya", "didapat", "didatangkan", "digunakan", "diibaratkan", "diibaratkannya",
    "diingat", "diingatkan", "diinginkan", "dijawab", "dijelaskan", "dijelaskannya", "dikarenakan",
    "dikatakan", "dikatakannya", "dikerjakan", "diketahui", "diketahuinya", "dikira", "dilakukan",
    "dilalui", "dilihat", "dimaksud", "dimaksudkan", "dimaksudkannya", "dimaksudnya", "diminta",
    "dimintai", "dimisalkan", "dimulai", "dimulailah", "dimulainya", "dimungkinkan", "dini",
    "dipastikan", "diperbuat", "diperbuatnya", "dipergunakan", "diperkirakan", "diperlihatkan",
    "diperlukan", "diperlukannya", "dipersoalkan", "dipunyai", "diri", "dirinya", "disampaikan",
    "disebut", "disebutkan", "disebutkannya", "disini", "disinilah", "disitu", "disitulah",
    "ditandaskan", "ditanya", "ditanyai", "ditanyakan", "ditegaskan", "ditemukan", "ditentukan",
    "dituturkan", "dituturkannya", "diucapkan", "diucapkannya", "diungkapkan", "dong", "dua",
    "dulu", "empat", "enggak", "enggaknya", "entah", "entahlah", "guna", "gunakan", "hal",
    "hampir", "hanya", "hanyalah", "hari", "harus", "haruslah", "harusnya", "hendak",
    "hendaklah", "hendaknya", "hingga", "ia", "ialah", "ibarat", "ibaratkan", "ibaratnya",
    "ibu", "ikut", "ingat", "ingin", "inginkah", "inginkan", "ini", "inikah", "inilah",
    "itu", "itukah", "itulah", "jadi", "jadilah", "jadinya", "jangan", "jangankan", "janganlah",
    "jauh", "jawab", "jawaban", "jawabnya", "jelas", "jelaskan", "jelaslah", "jelasnya",
    "jika", "jikalau", "juga", "jumlah", "jumlahnya", "justru", "kala", "kalau", "kalaulah",
    "kalaupun", "kalian", "kami", "kamilah", "kamu", "kamulah", "kan", "kapan", "kapankah",
    "kapanpun", "karena", "karenanya", "kasus", "kata", "katakan", "katakanlah", "katanya",
    "ke", "keadaan", "kebetulan", "kecil", "kedua", "keduanya", "keinginan", "kelen", "kelihatan",
    "kelihatannya", "kelima", "keluar", "kembali", "kemudian", "kemungkinan", "kemungkinannya",
    "kenapa", "kepada", "kepadanya", "kesampaian", "keseluruhan", "keseluruhannya", "keterlaluan",
    "ketika", "khususnya", "kini", "kinilah", "kira", "kiranya", "kita", "kitalah", "kok",
    "lagi", "lagian", "lah", "lain", "lainnya", "lalu", "lama", "lamanya", "lanjut", "lanjutnya",
    "lebih", "lewat", "lima", "luar", "macam", "maka", "makanya", "makin", "malah", "malahan",
    "mampu", "mampukah", "mana", "manakala", "manalagi", "masih", "masihkah", "masing",
    "mau", "maupun", "melainkan", "melakukan", "melalui", "melihat", "melihatnya", "memang",
    "memastikan", "memberi", "memberikan", "membuat", "memerlukan", "memihak", "meminta",
    "memintakan", "memisalkan", "memperbuat", "mempergunakan", "memperkirakan", "memperlihatkan",
    "mempersiapkan", "mempersoalkan", "mempertanyakan", "mempunyai", "memulai", "memungkinkan",
    "menaiki", "menandaskan", "menanti", "menantikan", "menanya", "menanyai", "menanyakan",
    "mendapat", "mendapatkan", "mendatang", "mendatangi", "mendatangkan", "menegaskan",
    "mengakhiri", "mengapa", "mengatakan", "mengatakannya", "mengenai", "mengerjakan",
    "mengetahui", "menggunakan", "menghendaki", "mengibaratkan", "mengibaratkannya", "mengingat",
    "mengingatkan", "menginginkan", "mengira", "mengucapkan", "mengucapkannya", "mengungkapkan",
    "menjadi", "menjawab", "menjelaskan", "menuju", "menunjuk", "menunjuki", "menunjukkan",
    "menunjuknya", "menurut", "menurutnya", "menyampaikan", "menyangkut", "menyatakan",
    "menyebutkan", "menyeluruh", "menyiapkan", "merasa", "mereka", "merekalah", "merupakan",
    "meski", "meskipun", "meyakini", "meyakinkan", "minta", "mirip", "misal", "misalkan",
    "misalnya", "mula", "mulai", "mulailah", "mulanya", "mungkin", "mungkinkah", "nah",
    "naik", "namun", "nanti", "nantinya", "nyaris", "nyatanya", "olah", "oleh", "olehnya",
    "pada", "padahal", "padanya", "pak", "paling", "panjang", "pantas", "para", "pasti",
    "pastilah", "penting", "pentingnya", "per", "para", "pernah", "pula", "pun", "punya",
    "rasa", "rasanya", "rupa", "rupanya", "saat", "saatnya", "saja", "sajalah", "saling",
    "sama", "sambil", "sampai", "sana", "sangat", "sangatlah", "saya", "sayalah", "se",
    "sebab", "sebabnya", "sebagai", "sebagaimana", "sebagainya", "sebagian", "sebaik",
    "sebaiknya", "sebaliknya", "sebanyak", "sebegini", "sebegitu", "sebelum", "sebelumnya",
    "sebenarnya", "seberapa", "sebesar", "sebetulnya", "sebisanya", "sebuah", "sebut",
    "sebutlah", "sebutnya", "secara", "secukupnya", "sedang", "sedangkan", "sedemikian",
    "sedikit", "sedikitnya", "seenaknya", "segala", "segalanya", "segera", "seharusnya",
    "sehingga", "seingat", "sejak", "sejauh", "sejenak", "sejumlah", "sekadar", "sekadarnya",
    "sekali", "sekalian", "sekaligus", "sekalipun", "sekarang", "sekaranglah", "sekiranya",
    "sekitar", "sekitarnya", "sekurang", "sekurangnya", "sela", "selain", "selalu", "selama",
    "selamanya", "selanjutnya", "seluruh", "seluruhnya", "semacam", "semakin", "semampu",
    "semampunya", "semasa", "semasih", "semata", "semisal", "sempat", "semua", "semuanya",
    "semula", "sendiri", "sendirian", "sendirinya", "seolah", "seorang", "sepanjang",
    "sepantasnya", "sepantasnyalah", "seperti", "sepertinya", "sepihak", "sering", "seringnya",
    "serta", "serupa", "sesaat", "sesama", "sesampai", "sesegera", "sesekali", "seseorang",
    "sesuatu", "sesuatunya", "sesudah", "sesudahnya", "setelah", "setempat", "setengah",
    "seterusnya", "setiap", "setiba", "setibanya", "setidak", "setidaknya", "setinggi",
    "seusai", "sewaktu", "siap", "siapa", "siapakah", "siapapun", "sini", "sinilah",
    "sinipun", "situ", "situlah", "suatu", "sudah", "sudahkah", "sudahlah", "supaya",
    "tadi", "tadinya", "tahu", "tak", "tambah", "tambahnya", "tampak", "tampaknya",
    "tandas", "tandasnya", "tanpa", "tanya", "tanyakan", "tanyanya", "tapi", "tegas",
    "tegasnya", "telah", "tempat", "tengah", "tentang", "tentu", "tentulah", "tentunya",
    "tepat", "terakhir", "terasa", "terbanyak", "terdahulu", "terdapat", "terdiri",
    "terhadap", "terhadapnya", "terjadi", "terjadilah", "terjadinya", "terkira", "terlalu",
    "terlebih", "terlihat", "termasuk", "ternyata", "tersampaikan", "tersebut", "tersebutlah",
    "tertentu", "tertuju", "terus", "terutama", "tetap", "tetapi", "tiap", "tiba",
    "tidak", "tidakkah", "tidaklah", "toh", "turut", "tutur", "tuturnya", "ucap",
    "ucapnya", "ujar", "ujarnya", "umum", "umumnya", "ungkap", "ungkapnya", "untuk",
    "usah", "usai", "waduh", "wah", "wahai", "waktunya", "walau", "walaupun", "wong",
    "yaitu", "yakin", "yakni", "yang", "yg", "dgn", "utk", "kpd", "dr", "dpt", "pd", "dlm"
}
